// SPDX-License-Identifier: MIT
//! Contract error types for the XLM Price Prediction Market.

use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ContractError {
    AlreadyInitialized = 1,
    AdminNotSet = 2,
    OracleNotSet = 3,
    InvalidBetAmount = 6,
    NoActiveRound = 7,
    RoundEnded = 8,
    InsufficientBalance = 9,
    AlreadyBet = 10,
    Overflow = 11,
    InvalidPrice = 12,
    InvalidDuration = 13,
    InvalidMode = 14,
    WrongModeForPrediction = 15,
    RoundNotEnded = 16,
    StaleOracleData = 18,
    InvalidOracleRound = 19,
    RoundAlreadyActive = 20,
    ContractPaused = 22,
    WindowOutOfRange = 23,
    FutureOracleData = 24,
    PayoutOverflow = 25,
    RoundNotCancellable = 27,
    StakeExceedsMax = 28,
    ExposureCapExceeded = 29,
    PendingWinningsCapExceeded = 30,
    InvalidStartPrice = 31,
    OracleNonceReused = 33,
    InvalidMinParticipants = 35,
    InvalidOracleStatus = 36,
    InvalidStaleThreshold = 37,
    InvalidPrecisionParticipantCap = 38,
    PrecisionCapExceeded = 39,
    InvalidOracleDeviationBps = 40,
    OracleDeviationExceeded = 41,
    UnsupportedSchemaVersion = 42,
    OracleDataBeforeRound = 43,
    MigrationActiveRound = 44,
    CommitmentNotFound = 45,
    AlreadyRevealed = 46,
    InvalidRevealWindow = 47,
    HashMismatch = 48,
    OracleNetworkMismatch = 49,
    OracleContractMismatch = 50,
    InvalidProtocolFeeBps = 51,
    MintLimitExceeded = 53,
    NoPendingRotation = 54,
    RotationExpired = 55,
    AdminIsOracle = 56,
    InvalidMigrationPath = 57,
    StartPriceTooLow = 58,
    StartPriceTooHigh = 59,
    InvalidPriceScale = 60,
    FeeTreasuryUnderflow = 61,
    InvalidArchiveRetention = 62,
}\r\n\r\n#[allow(non_upper_case_globals)]\r\nimpl ContractError {\r\n    pub const PrecisionParticipantCapExceeded: Self = Self::PrecisionCapExceeded;\r\n}\r\n
