// SPDX-License-Identifier: MIT
//! Contract error types for the XLM Price Prediction Market.

use soroban_sdk::{ConversionError, Env, Error, IntoVal, TryFromVal, Val};

/// Contract error types
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ContractError {
    AlreadyInitialized = 1,
    AdminNotSet = 2,
    OracleNotSet = 3,
    InvalidBetAmount = 6,
    NoActiveRound = 7,
    RoundEnded = 8,
    InsufficientBalance = 9,
    AlreadyBet = 10,
    Overflow = 11,
    InvalidPrice = 12,
    InvalidDuration = 13,
    InvalidMode = 14,
    WrongModeForPrediction = 15,
    RoundNotEnded = 16,
    StaleOracleData = 18,
    InvalidOracleRound = 19,
    RoundAlreadyActive = 20,
    ContractPaused = 22,
    WindowOutOfRange = 23,
    FutureOracleData = 24,
    PayoutOverflow = 25,
    RoundNotCancellable = 27,
    StakeExceedsMax = 28,
    ExposureCapExceeded = 29,
    PendingWinningsCapExceeded = 30,
    InvalidStartPrice = 31,
    OracleNonceReused = 33,
    InvalidMinParticipants = 35,
    InvalidPrecisionCap = 38,
    PrecisionCapExceeded = 39,
    OracleDeviationExceeded = 41,
    UnsupportedSchemaVersion = 42,
    MigrationActiveRound = 44,
    CommitmentNotFound = 45,
    AlreadyRevealed = 46,
    InvalidRevealWindow = 47,
    HashMismatch = 48,
    OracleNetworkMismatch = 49,
    InvalidProtocolFeeBps = 51,
    MintLimitExceeded = 53,
    NoPendingRotation = 54,
    RotationDelayNotElapsed = 55,
    InvalidArchiveRetention = 62,
    InvalidCommitment = 63,
    InvalidSalt = 64,
    NoRoundTemplate = 65,
    OracleTimestampOutsideWindow = 66,
    PendingWinningsNotExpired = 67,
    EpochBudgetExceeded = 68,
    OracleNotLive = 69,
    InvalidPayoutPolicy = 70,
    BelowMinBet = 71,
    InsufficientOracleQuorum = 72,
    TooFewObservations = 73,
    OracleOutlierRejected = 74,
    DuplicateOracleSource = 75,
    InvalidObservationOrder = 76,
    UnsupportedDataKeyForTtlTouch = 77,
    PendingWinningsNotFound = 78,
    ExpiryNotConfigured = 79,
    // ─── Intent / Keeper Authorization Zone errors (Issue #370) ──────────────
    IntentAlreadyConsumed = 80,
    IntentExpired = 81,
    IntentRevoked = 82,
    IntentKeeperMismatch = 83,
    IntentScopeMismatch = 84,
    KeeperNotRegistered = 85,
    InvalidIntentExpiry = 86,
    IntentNotFound = 87,
    // ─── Additional Governance, Dispute & Access Control Errors ─────────────
    GovUnauthorized = 88,
    GovProposalNotFound = 89,
    GovProposalExpired = 90,
    GovInvalidState = 91,
    GovSelfApprovalDenied = 92,
    DisputeWindowExpired = 93,
    ClaimLocked = 94,
    AccessDenied = 95,
    InvalidAmount = 96,
    ProposalNotFound = 97,
    ProposalExpired = 98,
    OracleHeartbeatUnhealthy = 99,
}

impl From<ContractError> for Error {
    fn from(e: ContractError) -> Self {
        Error::from_contract_error(e as u32)
    }
}

impl From<&ContractError> for Error {
    fn from(e: &ContractError) -> Self {
        Error::from_contract_error(*e as u32)
    }
}

impl TryFrom<Error> for ContractError {
    type Error = Error;
    fn try_from(err: Error) -> Result<Self, Self::Error> {
        let code = err.get_code();
        match code {
            1 => Ok(ContractError::AlreadyInitialized),
            2 => Ok(ContractError::AdminNotSet),
            3 => Ok(ContractError::OracleNotSet),
            6 => Ok(ContractError::InvalidBetAmount),
            7 => Ok(ContractError::NoActiveRound),
            8 => Ok(ContractError::RoundEnded),
            9 => Ok(ContractError::InsufficientBalance),
            10 => Ok(ContractError::AlreadyBet),
            11 => Ok(ContractError::Overflow),
            12 => Ok(ContractError::InvalidPrice),
            13 => Ok(ContractError::InvalidDuration),
            14 => Ok(ContractError::InvalidMode),
            15 => Ok(ContractError::WrongModeForPrediction),
            16 => Ok(ContractError::RoundNotEnded),
            18 => Ok(ContractError::StaleOracleData),
            19 => Ok(ContractError::InvalidOracleRound),
            20 => Ok(ContractError::RoundAlreadyActive),
            22 => Ok(ContractError::ContractPaused),
            23 => Ok(ContractError::WindowOutOfRange),
            24 => Ok(ContractError::FutureOracleData),
            25 => Ok(ContractError::PayoutOverflow),
            27 => Ok(ContractError::RoundNotCancellable),
            28 => Ok(ContractError::StakeExceedsMax),
            29 => Ok(ContractError::ExposureCapExceeded),
            30 => Ok(ContractError::PendingWinningsCapExceeded),
            31 => Ok(ContractError::InvalidStartPrice),
            33 => Ok(ContractError::OracleNonceReused),
            35 => Ok(ContractError::InvalidMinParticipants),
            38 => Ok(ContractError::InvalidPrecisionCap),
            39 => Ok(ContractError::PrecisionCapExceeded),
            41 => Ok(ContractError::OracleDeviationExceeded),
            42 => Ok(ContractError::UnsupportedSchemaVersion),
            44 => Ok(ContractError::MigrationActiveRound),
            45 => Ok(ContractError::CommitmentNotFound),
            46 => Ok(ContractError::AlreadyRevealed),
            47 => Ok(ContractError::InvalidRevealWindow),
            48 => Ok(ContractError::HashMismatch),
            49 => Ok(ContractError::OracleNetworkMismatch),
            51 => Ok(ContractError::InvalidProtocolFeeBps),
            53 => Ok(ContractError::MintLimitExceeded),
            54 => Ok(ContractError::NoPendingRotation),
            55 => Ok(ContractError::RotationDelayNotElapsed),
            62 => Ok(ContractError::InvalidArchiveRetention),
            63 => Ok(ContractError::InvalidCommitment),
            64 => Ok(ContractError::InvalidSalt),
            65 => Ok(ContractError::NoRoundTemplate),
            66 => Ok(ContractError::OracleTimestampOutsideWindow),
            67 => Ok(ContractError::PendingWinningsNotExpired),
            68 => Ok(ContractError::EpochBudgetExceeded),
            69 => Ok(ContractError::OracleNotLive),
            70 => Ok(ContractError::InvalidPayoutPolicy),
            71 => Ok(ContractError::BelowMinBet),
            72 => Ok(ContractError::InsufficientOracleQuorum),
            73 => Ok(ContractError::TooFewObservations),
            74 => Ok(ContractError::OracleOutlierRejected),
            75 => Ok(ContractError::DuplicateOracleSource),
            76 => Ok(ContractError::InvalidObservationOrder),
            77 => Ok(ContractError::UnsupportedDataKeyForTtlTouch),
            78 => Ok(ContractError::PendingWinningsNotFound),
            79 => Ok(ContractError::ExpiryNotConfigured),
            80 => Ok(ContractError::IntentAlreadyConsumed),
            81 => Ok(ContractError::IntentExpired),
            82 => Ok(ContractError::IntentRevoked),
            83 => Ok(ContractError::IntentKeeperMismatch),
            84 => Ok(ContractError::IntentScopeMismatch),
            85 => Ok(ContractError::KeeperNotRegistered),
            86 => Ok(ContractError::InvalidIntentExpiry),
            87 => Ok(ContractError::IntentNotFound),
            88 => Ok(ContractError::GovUnauthorized),
            89 => Ok(ContractError::GovProposalNotFound),
            90 => Ok(ContractError::GovProposalExpired),
            91 => Ok(ContractError::GovInvalidState),
            92 => Ok(ContractError::GovSelfApprovalDenied),
            93 => Ok(ContractError::DisputeWindowExpired),
            94 => Ok(ContractError::ClaimLocked),
            95 => Ok(ContractError::AccessDenied),
            96 => Ok(ContractError::InvalidAmount),
            97 => Ok(ContractError::ProposalNotFound),
            98 => Ok(ContractError::ProposalExpired),
            99 => Ok(ContractError::OracleHeartbeatUnhealthy),
            _ => Err(err),
        }
    }
}

impl IntoVal<Env, Val> for ContractError {
    fn into_val(&self, env: &Env) -> Val {
        Error::from_contract_error(*self as u32).into_val(env)
    }
}

impl TryFromVal<Env, Val> for ContractError {
    type Error = ConversionError;
    fn try_from_val(env: &Env, val: &Val) -> Result<Self, Self::Error> {
        let err: Error = Error::try_from_val(env, val)?;
        let code = err.get_code();
        match code {
            1 => Ok(ContractError::AlreadyInitialized),
            2 => Ok(ContractError::AdminNotSet),
            3 => Ok(ContractError::OracleNotSet),
            6 => Ok(ContractError::InvalidBetAmount),
            7 => Ok(ContractError::NoActiveRound),
            8 => Ok(ContractError::RoundEnded),
            9 => Ok(ContractError::InsufficientBalance),
            10 => Ok(ContractError::AlreadyBet),
            11 => Ok(ContractError::Overflow),
            12 => Ok(ContractError::InvalidPrice),
            13 => Ok(ContractError::InvalidDuration),
            14 => Ok(ContractError::InvalidMode),
            15 => Ok(ContractError::WrongModeForPrediction),
            16 => Ok(ContractError::RoundNotEnded),
            18 => Ok(ContractError::StaleOracleData),
            19 => Ok(ContractError::InvalidOracleRound),
            20 => Ok(ContractError::RoundAlreadyActive),
            22 => Ok(ContractError::ContractPaused),
            23 => Ok(ContractError::WindowOutOfRange),
            24 => Ok(ContractError::FutureOracleData),
            25 => Ok(ContractError::PayoutOverflow),
            27 => Ok(ContractError::RoundNotCancellable),
            28 => Ok(ContractError::StakeExceedsMax),
            29 => Ok(ContractError::ExposureCapExceeded),
            30 => Ok(ContractError::PendingWinningsCapExceeded),
            31 => Ok(ContractError::InvalidStartPrice),
            33 => Ok(ContractError::OracleNonceReused),
            35 => Ok(ContractError::InvalidMinParticipants),
            38 => Ok(ContractError::InvalidPrecisionCap),
            39 => Ok(ContractError::PrecisionCapExceeded),
            41 => Ok(ContractError::OracleDeviationExceeded),
            42 => Ok(ContractError::UnsupportedSchemaVersion),
            44 => Ok(ContractError::MigrationActiveRound),
            45 => Ok(ContractError::CommitmentNotFound),
            46 => Ok(ContractError::AlreadyRevealed),
            47 => Ok(ContractError::InvalidRevealWindow),
            48 => Ok(ContractError::HashMismatch),
            49 => Ok(ContractError::OracleNetworkMismatch),
            51 => Ok(ContractError::InvalidProtocolFeeBps),
            53 => Ok(ContractError::MintLimitExceeded),
            54 => Ok(ContractError::NoPendingRotation),
            55 => Ok(ContractError::RotationDelayNotElapsed),
            62 => Ok(ContractError::InvalidArchiveRetention),
            63 => Ok(ContractError::InvalidCommitment),
            64 => Ok(ContractError::InvalidSalt),
            65 => Ok(ContractError::NoRoundTemplate),
            66 => Ok(ContractError::OracleTimestampOutsideWindow),
            67 => Ok(ContractError::PendingWinningsNotExpired),
            68 => Ok(ContractError::EpochBudgetExceeded),
            69 => Ok(ContractError::OracleNotLive),
            70 => Ok(ContractError::InvalidPayoutPolicy),
            71 => Ok(ContractError::BelowMinBet),
            72 => Ok(ContractError::InsufficientOracleQuorum),
            73 => Ok(ContractError::TooFewObservations),
            74 => Ok(ContractError::OracleOutlierRejected),
            75 => Ok(ContractError::DuplicateOracleSource),
            76 => Ok(ContractError::InvalidObservationOrder),
            77 => Ok(ContractError::UnsupportedDataKeyForTtlTouch),
            78 => Ok(ContractError::PendingWinningsNotFound),
            79 => Ok(ContractError::ExpiryNotConfigured),
            80 => Ok(ContractError::IntentAlreadyConsumed),
            81 => Ok(ContractError::IntentExpired),
            82 => Ok(ContractError::IntentRevoked),
            83 => Ok(ContractError::IntentKeeperMismatch),
            84 => Ok(ContractError::IntentScopeMismatch),
            85 => Ok(ContractError::KeeperNotRegistered),
            86 => Ok(ContractError::InvalidIntentExpiry),
            87 => Ok(ContractError::IntentNotFound),
            88 => Ok(ContractError::GovUnauthorized),
            89 => Ok(ContractError::GovProposalNotFound),
            90 => Ok(ContractError::GovProposalExpired),
            91 => Ok(ContractError::GovInvalidState),
            92 => Ok(ContractError::GovSelfApprovalDenied),
            93 => Ok(ContractError::DisputeWindowExpired),
            94 => Ok(ContractError::ClaimLocked),
            95 => Ok(ContractError::AccessDenied),
            96 => Ok(ContractError::InvalidAmount),
            97 => Ok(ContractError::ProposalNotFound),
            98 => Ok(ContractError::ProposalExpired),
            99 => Ok(ContractError::OracleHeartbeatUnhealthy),
            _ => Err(ConversionError),
        }
    }
}
